### ISSUE TITLE
No longer compiles with libxslt 1.30

### ISSUE THREAD

**Issue by graaff** [glejeune/ruby-xslt#7]
In this version the norm:Localtime function was removed, and thus XSLT_NORM_SAXON_NAMESPACE is no longer defined, leading to a compilation error.

```
x86_64-pc-linux-gnu-gcc -I. -I/usr/include/ruby-2.2.0/x86_64-linux -I/usr/include/ruby-2.2.0/ruby/backward -I/usr/include/ruby-2.2.0 -I. -DRUBY_EXTCONF_H=\"extconf.h\"    -fPIC -Wall -I/usr/include/libxml2 -I/usr/include/libxml2 -Wall -O2 -pipe -march=native -Wformat-security -ggdb -fno-strict-aliasing -fPIC -DUSE_ERROR_HANDLER -DUSE_EXSLT  -o extfunc.o -c extfunc.c
xslt_lib.c: In function ‘Init_xslt_lib’:
xslt_lib.c:564:99: error: ‘XSLT_NORM_SAXON_NAMESPACE’ undeclared (first use in this function)
   rb_define_const( cXSLT, "NAMESPACE_NORM_SAXON", rb_str_new2((char *)XSLT_NORM_SAXON_NAMESPACE) );
                                                                                                   ^
xslt_lib.c:564:99: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:237: xslt_lib.o] Error 1
```

https://mail.gnome.org/archives/commits-list/2017-February/msg00373.html has the libxslt upstream patch.

Removing the line declaring the XSLT_NORM_SAXON_NAMESPACE appears to be sufficient because it does not seem to be used otherwise.
